GET /residents/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber": 8,
  "name": "abc",
  "residentRegistrationNumber": "981008-8910123",
  "genderCode": "남",
  "birthDate": "1998-10-08T10:11:30",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "광주 광역시 북구 용봉동",
  "deathDate": null,
  "deathPlaceCode": null,
  "deathPlaceAddress": null
}

###

PUT localhost:8080/residents/8
Content-Type: application/json

{
  "name": "변경된 abc",
  "deathDate": "2022-12-31T11:05:30",
  "deathPlaceCode": "고속도로",
  "deathPlaceAddress": "서해안 고속도로"
}

###

DELETE localhost:8080/residents/8

###
# 계정 추가
# 1번 주민 ~ 7번 주민
# 100번 주민 ~ 107번 주민

PUT localhost:8080/residents/add/account/107
Content-Type: application/json

{
  "id": "a107",
  "password": "p107",
  "email": "a107@naver.com"
}