GET /posts?page=0&size=5
Content-Type: application/json
Host: localhost:8080

###

GET /posts?page=1&size=5
Content-Type: application/json
Host: localhost:8080

###

GET /posts?page=2&size=5
Content-Type: application/json
Host: localhost:8080
